// This is a instance file generated by scripy file 'InstModule'.
Ctrl Ctrl_inst(
	// system signal
	.sys_clk				(sys_clk				),	// i 1b
	.sys_rst_n				(sys_rst_n				),	// i 1b
	// dataflow
	.data1_in				(data1_in				),	// i 32b
	.data2_in				(data2_in				),	// i 32b
	.plus_result_in			(plus_result_in			),	// i 32b
	.multi_result_in		(multi_result_in		),	// i 32b
	.div_result_in			(div_result_in			),	// i 32b
	.data1_out				(data1_out				),	// o 32b
	.data2_out				(data2_out				),	// o 32b
	.result_out				(result_out				),	// o 32b
	// control
	.opcode					(opcode					),	// i 2b
	.trig					(trig					),	// i 1b
	.plus_vld_in			(plus_vld_in			),	// i 1b
	.multi_vld_in			(multi_vld_in			),	// i 1b
	.div_vld_in				(div_vld_in				),	// i 1b
	.multi_unit_sel			(multi_unit_sel			),	// o 1b
	.sel_plus				(sel_plus				),	// o 1b
	.sel_multi				(sel_multi				),	// o 1b
	.sel_dev				(sel_dev				),	// o 1b
	.op_plus				(op_plus				),	// o 1b
	.work					(work					),	// o 1b
	.result_vld				(result_vld				)	// o 1b
);